import esbuild from "esbuild";
import builtins from "builtin-modules";
import { createHash } from "node:crypto";
import { access, copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const args = new Set(process.argv.slice(2));
const production = args.has("production");
const watch = process.argv.includes("--watch");
const rootDir = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(rootDir, "dist");
const generatedPreloadSourceModulePath = resolve(
  rootDir,
  "src",
  "generated",
  "desktop-pet-preload-source.ts"
);
const staticArtifacts = ["manifest.json", "styles.css", "versions.json"];
const obsoleteDistArtifacts = ["desktop-pet-preload.js"];

async function copyStaticArtifacts() {
  await mkdir(distDir, { recursive: true });

  await Promise.all(
    staticArtifacts.map(async (fileName) => {
      const sourcePath = resolve(rootDir, fileName);
      try {
        await access(sourcePath);
      } catch (error) {
        if (error instanceof Error && "code" in error && error.code === "ENOENT") {
          return;
        }
        throw error;
      }

      await copyFile(sourcePath, resolve(distDir, fileName));
    })
  );
}

async function removeObsoleteDistArtifacts() {
  await Promise.all(
    obsoleteDistArtifacts.map((fileName) =>
      rm(resolve(distDir, fileName), { force: true })
    )
  );
}

const copyStaticArtifactsPlugin = {
  name: "copy-static-artifacts",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;
      await copyStaticArtifacts();
    });
  }
};

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtins,
  ...builtins.map((moduleName) => `node:${moduleName}`)
];

async function bundleDesktopPetPreloadSource() {
  const result = await esbuild.build({
    banner: {
      js: "/* Petsidian desktop pet preload bridge */"
    },
    entryPoints: ["src/desktop-pet-preload.ts"],
    bundle: true,
    external,
    format: "cjs",
    logLevel: "silent",
    platform: "node",
    sourcemap: false,
    target: "es2018",
    write: false
  });
  const outputFile = result.outputFiles[0];
  if (outputFile === undefined) {
    throw new Error("Failed to bundle desktop pet preload source.");
  }
  const source =
    "/* Generated at build time from src/desktop-pet-preload.ts. */\n" +
    `${outputFile.text.trimEnd()}\n`;
  return {
    source,
    sha256: createHash("sha256").update(source).digest("hex")
  };
}

async function generateDesktopPetPreloadSourceModule() {
  const { source, sha256 } = await bundleDesktopPetPreloadSource();
  const moduleSource = [
    "// Generated by esbuild.config.mjs. Do not edit by hand.",
    `export const DESKTOP_PET_PRELOAD_SOURCE = ${JSON.stringify(source)};`,
    `export const DESKTOP_PET_PRELOAD_SHA256 = ${JSON.stringify(sha256)};`,
    ""
  ].join("\n");

  try {
    const currentSource = await readFile(generatedPreloadSourceModulePath, "utf8");
    if (currentSource === moduleSource) {
      return;
    }
  } catch (error) {
    if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") {
      throw error;
    }
  }

  await mkdir(dirname(generatedPreloadSourceModulePath), { recursive: true });
  await writeFile(generatedPreloadSourceModulePath, moduleSource, "utf8");
}

if (args.has("--generate-preload-source")) {
  await generateDesktopPetPreloadSourceModule();
  process.exit(0);
}

const generatePreloadSourcePlugin = {
  name: "generate-preload-source",
  setup(build) {
    build.onStart(async () => {
      await generateDesktopPetPreloadSourceModule();
      await removeObsoleteDistArtifacts();
    });
  }
};

const context = await esbuild.context({
  banner: {
    js: "/* Petsidian - Obsidian native plugin */"
  },
  entryPoints: {
    main: "src/main.ts"
  },
  bundle: true,
  external,
  entryNames: "[name]",
  format: "cjs",
  loader: {
    ".webp": "dataurl"
  },
  target: "es2018",
  logLevel: "info",
  minify: production,
  plugins: [generatePreloadSourcePlugin, copyStaticArtifactsPlugin],
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outdir: distDir
});

if (watch) {
  await context.watch();
  console.log("Watching for changes in dist/...");
} else {
  await context.rebuild();
  await context.dispose();
}
